name: Generate Datas
on:
  schedule:
    - cron: "0 */12 * * *" # run every 12 hours at the start of the hour
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: G-S-LTU
          svg_out_path: dist/github-contribution-grid-snake.svg
      
      # Ensure the 'dist' directory exists
      - name: Create dist directory
        run: mkdir -p dist

      # Upload the generated snake.svg to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
